# Generated by Django 3.2.10 on 2022-01-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_alter_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mon',
        ),
    ]
