# Generated by Django 3.2.10 on 2022-01-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_auto_20220109_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=int, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='blogs'),
        ),
    ]
