# Generated by Django 3.2.10 on 2022-01-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20220110_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='name',
        ),
    ]
