# Generated by Django 3.2.10 on 2022-01-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_rename_title_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
