# Generated by Django 3.2.10 on 2022-01-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_alter_blog_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
